@startuml

!include ./dist/common.puml
' it is allowed to include all.puml - rather than an include per object.
' !include dist/all.puml
!include ./dist/v8_AccRg.puml
!include ./dist/v8_Document.puml
!include ./dist/v8_Catalog.puml
!include ./dist/v8_InfoRg.puml

title 1С: ERP 2.5
caption НСИ и документы
package ТМЦ <<Rectangle>> #ffff99 {
    _Справочник(Номенклатура)
    _Справочник(ВидыНоменклатуры, "Виды номенклатуры")
    _Справочник(одКлассыРентабельностиНоменклатуры, "Классы рентабельности номенклатуры")
    _Документ(ПриобретениеТоваровУслуг, "Приобретение товаров и услуг")
    _Документ(ИзменениеАссортимента, "Изменение ассортимента")
    _РегистрСведений(Ассортимент)
    _РегистрНакопления(СвободныеОстатки, "Свободные остатки")
    
    Номенклатура : Ссылка
    ВидыНоменклатуры : Ссылка
    одКлассыРентабельностиНоменклатуры : Ссылка
}

package Взаиморасчеты <<Rectangle>> #b3c6ff {
    _Справочник(ДоговорыСКонтрагентами, "Договоры с контрагентами")
    _Справочник(Контрагенты)

    Контрагенты : Ссылка
    ДоговорыСКонтрагентами : Ссылка
    ДоговорыСКонтрагентами : Контрагент
}

ВидыНоменклатуры-->Номенклатура : Владелец
Номенклатура-->одКлассыРентабельностиНоменклатуры
Контрагенты-->ДоговорыСКонтрагентами

ПриобретениеТоваровУслуг-down->СвободныеОстатки : "Приход"
ИзменениеАссортимента-down->Ассортимент

@enduml
